export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  CREATE_USER: "CREATE_USER",
  VIEW_USERS: "VIEW_USERS",
  EDIT_USER: "EDIT_USER",
  DEACTIVATE_USER: "DEACTIVATE_USER",
  CREATE_COMPANY: "CREATE_COMPANY",
  VIEW_COMPANIES: "VIEW_COMPANIES",
  EDIT_COMPANY: "EDIT_COMPANY",
  DEACTIVATE_COMPANY: "DEACTIVATE_COMPANY",
  MANAGE_ROLES: "MANAGE_ROLES",
} as const;

export type Permission = keyof typeof PERMISSIONS;